default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: heroku_sample_development

test:
  <<: *default
  database: heroku_sample_test

production:
  <<: *default
  database: heroku_sample_production
  username: heroku_sample
  password: <%= ENV['HEROKU_SAMPLE_DATABASE_PASSWORD'] %>
